// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0Tm3Wuo-3zY8qoqOU6XZpd1YBF-wQveA',
    appId: '1:442464094209:web:ea5965015eb571d62d9800',
    messagingSenderId: '442464094209',
    projectId: 'login-first-8195d',
    authDomain: 'login-first-8195d.firebaseapp.com',
    storageBucket: 'login-first-8195d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_bznorEwmLqg0RzBvf1GwLZxILguszjw',
    appId: '1:442464094209:android:b505b37f750258a12d9800',
    messagingSenderId: '442464094209',
    projectId: 'login-first-8195d',
    storageBucket: 'login-first-8195d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoV44h4fa5hAnRHZC6Wi-5uTZUZe2AG9U',
    appId: '1:442464094209:ios:3f559b6abab1f0d62d9800',
    messagingSenderId: '442464094209',
    projectId: 'login-first-8195d',
    storageBucket: 'login-first-8195d.appspot.com',
    iosBundleId: 'com.example.loginApi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoV44h4fa5hAnRHZC6Wi-5uTZUZe2AG9U',
    appId: '1:442464094209:ios:033a34d577d158e62d9800',
    messagingSenderId: '442464094209',
    projectId: 'login-first-8195d',
    storageBucket: 'login-first-8195d.appspot.com',
    iosBundleId: 'com.example.loginApi.RunnerTests',
  );
}
